application: time-stat
version: 1
runtime: go
api_version: go1

handlers:
- url: /task/reset
  script: _go_app
  login: admin
- url: /css
  static_dir: ../ui/resources/public/css
- url: /js
  static_dir: ../ui/resources/public/js
- url: /.*
  script: _go_app
  login: required
  secure: always
